# Generated by Django 3.0.8 on 2020-10-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blogs/default.jpeg', upload_to='blogs/'),
        ),
    ]
