# Generated by Django 3.0.8 on 2020-10-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blogs/default.jpg', upload_to='blogs/'),
        ),
    ]
